name: Test Run

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: yarn install
      - run: npx resume export --theme . --resume ./test/fixture.resume.json /tmp/resume.html
      - run: npx resume export --theme . --resume ./test/fixture.resume.json /tmp/resume.pdf
